#!/usr/bin/env python
import csv
import sys

headers = []

last_color = None
for (name, color, _, _, _, _, _) in csv.reader(iter(sys.stdin.readline, '')):
    color = color.title().replace('_', ' ')

    if last_color is not None and last_color != color:
        print ''

    if color not in headers:
        print '### ' + color + '\n'
        headers.append(color)

    print '  - [x] ' + name + ' ( )'
    last_color = color
